// Generated by github.com/davyxu/tabtoy
// Version: 2.8.10

module table {
export var TTask : table.ITTaskDefine[] = [
		{ Id : 1001, MainTask : 1000, SubTask : 1, Count : 1, Desc : "分享1次", Reward : "6001-2000" 	},
		{ Id : 1002, MainTask : 1000, SubTask : 2, Count : 1, Desc : "分享1次", Reward : "6001-2000" 	},
		{ Id : 1003, MainTask : 1000, SubTask : 3, Count : 1, Desc : "分享1次", Reward : "6001-2000" 	},
		{ Id : 1004, MainTask : 1000, SubTask : 4, Count : 1, Desc : "分享1次", Reward : "6001-2000" 	},
		{ Id : 1005, MainTask : 1000, SubTask : 5, Count : 1, Desc : "分享1次", Reward : "6001-2000" 	},
		{ Id : 1006, MainTask : 1000, SubTask : 6, Count : 1, Desc : "分享1次", Reward : "6001-2000" 	},
		{ Id : 1007, MainTask : 1000, SubTask : 7, Count : 1, Desc : "分享1次", Reward : "6001-2000" 	},
		{ Id : 1008, MainTask : 1000, SubTask : 8, Count : 1, Desc : "分享1次", Reward : "6001-2000" 	},
		{ Id : 1009, MainTask : 1000, SubTask : 9, Count : 1, Desc : "分享1次", Reward : "6001-2000" 	},
		{ Id : 1010, MainTask : 1000, SubTask : 10, Count : 1, Desc : "分享1次", Reward : "6001-2000" 	},
		{ Id : 2001, MainTask : 2000, SubTask : 1, Count : 1, Desc : "获得比赛最终胜利1次", Reward : "6001-1000" 	},
		{ Id : 2002, MainTask : 2000, SubTask : 2, Count : 2, Desc : "获得比赛最终胜利2次", Reward : "6001-2000" 	},
		{ Id : 2003, MainTask : 2000, SubTask : 3, Count : 3, Desc : "获得比赛最终胜利3次", Reward : "6001-3000" 	},
		{ Id : 2004, MainTask : 2000, SubTask : 4, Count : 5, Desc : "获得比赛最终胜利4次", Reward : "6001-4000" 	},
		{ Id : 3001, MainTask : 3000, SubTask : 1, Count : 3, Desc : "参加3局比赛", Reward : "6001-1000" 	},
		{ Id : 3002, MainTask : 3000, SubTask : 2, Count : 5, Desc : "参加5局比赛", Reward : "6001-2000" 	},
		{ Id : 3003, MainTask : 3000, SubTask : 3, Count : 7, Desc : "参加7局比赛", Reward : "6001-3000" 	},
		{ Id : 3004, MainTask : 3000, SubTask : 4, Count : 10, Desc : "参加10局比赛", Reward : "6001-4000" 	},
		{ Id : 4001, MainTask : 4000, SubTask : 1, Count : 1000, Desc : "比赛中赢得1000金币", Reward : "6001-1000" 	},
		{ Id : 4002, MainTask : 4000, SubTask : 2, Count : 2000, Desc : "比赛中赢得2000金币", Reward : "6001-2000" 	},
		{ Id : 4003, MainTask : 4000, SubTask : 3, Count : 5000, Desc : "比赛中赢得3000金币", Reward : "6001-3000" 	},
		{ Id : 4004, MainTask : 4000, SubTask : 4, Count : 10000, Desc : "比赛中赢得4000金币", Reward : "6001-4000" 	},
		{ Id : 5001, MainTask : 5000, SubTask : 1, Count : 10, Desc : "淘汰10名玩家", Reward : "6001-1000" 	},
		{ Id : 5002, MainTask : 5000, SubTask : 2, Count : 50, Desc : "淘汰50名玩家", Reward : "6001-2000" 	},
		{ Id : 5003, MainTask : 5000, SubTask : 3, Count : 100, Desc : "淘汰100名玩家", Reward : "6001-3000" 	},
		{ Id : 5004, MainTask : 5000, SubTask : 4, Count : 200, Desc : "淘汰200名玩家", Reward : "6001-4000" 	}
	]


// Id
export var TTaskById : game.Dictionary<table.ITTaskDefine> = {}
function readTTaskById(){
  for(let rec of TTask) {
    TTaskById[rec.Id] = rec; 
  }
}
readTTaskById();
}

